layout_spectrum: 0.4514925
color:
  saturation: 0.7915112
  lightness: 0.2117537
  brandStrength: 1
  brandColors:
    - '#342C29'
    - '#E9A9BC'
    - '#E4D824'
    - '#A46E5D'
    - '#3C943A'
  rhythmicContrast: 0.0442619
typography_spectrum: 0.125
name: Frances Cole Photography
